<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Nova.Server</AssemblyName>
    <RootNamespace>Nova.Server</RootNamespace>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <OutputPath>..\Build\Debug\</OutputPath>
    <BaseOutputPath>..\Build\</BaseOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <OutputPath>..\Build\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\VersionInfo.cs" Link="VersionInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\ControlLibrary\ControlLibrary.csproj" />
  </ItemGroup>

</Project>
